### PR TITLE
Add support for a non greedy operator

### PR DESCRIPTION
**Pull request by dmmiller**

### CODE REVIEW

**Comment by ryan-lane** [comment]
Ah, this is great. Can you update the commit description to give a basic idea of what you're adding support for? The tests help, but for looking through git history this will help.

**Review by ryan-lane — APPROVED** [review]
I'm pretty sure I don't have reviewer privileges on this repo anymore, but the changes look good to me. You'll probably have to track someone down from lyft.

**Comment by dmmiller** [comment]
cc  @colinsl as I think you have approval capability

**Comment by dmmiller** [comment]
Updated the commit message, per @ryan-lane 's request although github ui doesn't show it.

**Comment by colinsl** [comment]
👍

**Comment by dmmiller** [comment]
hmm, was hoping that @colinsl was an approving review.   Maybe this doesn't support +1 approval since it is  also open source?

**Comment by ryan-lane** [comment]
You may want to check what groups are allowed to +1. For open source, I think we had teams setup for this.

**Review by colinsl — APPROVED** [review]

**Review by colinsl — APPROVED** [review]

**Pull request merged**
